Repository flaskbb/flaskbb, pull requests merged in 2018-06, with the labels that each got.

#472 Polish registration hooks
  docs/development/api/registration.rst
  docs/development/hooks/event.rst
  flaskbb/auth/plugins.py
  flaskbb/auth/services/factories.py
  flaskbb/auth/services/registration.py
  flaskbb/auth/views.py
  flaskbb/core/auth/registration.py
  flaskbb/core/exceptions.py
  flaskbb/core/user/__init__.py
  flaskbb/core/user/repo.py
  flaskbb/plugins/spec.py
  flaskbb/templates/layout.html
  flaskbb/user/repo.py
  tests/fixtures/plugin.py
  tests/fixtures/user.py
  tests/unit/auth/test_authentication.py
  tests/unit/auth/test_reauthentication.py
  tests/unit/auth/test_registration.py
  tests/unit/auth/test_registration_processors.py
Labels: feature, hook

#481 Restore ability to activate account through form submit
  flaskbb/auth/forms.py
  flaskbb/auth/views.py
  flaskbb/templates/email/activate_account.html
  flaskbb/templates/email/activate_account.txt
Labels: bug, cleanup

#474 Add deprecation helper
  docs/contents.rst.inc
  docs/development/api/deprecations.rst
  docs/development/api/index.rst
  docs/releases.rst
  flaskbb/app.py
  flaskbb/cli/main.py
  flaskbb/configs/config.cfg.template
  flaskbb/deprecation.py
  flaskbb/user/models.py
  requirements.txt
  tests/unit/test_deprecation.py
  tox.ini
Labels: documentation, feature

#477 Add support for rendering markdown previews server side
  flaskbb/forum/forms.py
  flaskbb/forum/views.py
  flaskbb/static/js/scripts.min.js
  flaskbb/templates/forum/topic.html
  flaskbb/templates/layout.html
  flaskbb/themes/aurora/src/js/editor.js
Labels: enhancement, feature
